const r = require('express').Router();
const auth = require('../middleware/auth');
const c = require('../controllers/template.controller');
r.use(auth);
r.get('/', c.list);
r.post('/', c.create);
r.get('/:id', c.get);
r.put('/:id', c.update);
r.delete('/:id', c.remove);
module.exports = r;
